#include <stdio.h>
#include <math.h>

/*


Pentagonal numbers are generated by the formula, Pn=n(3n−1)/2. The first ten pentagonal numbers are:

1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...

It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 − 22 = 48, is not pentagonal.

Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal 
and D = |Pk − Pj| is minimised; what is the value of D?

*/

int is_pentagonal(unsigned long long int n){
	double t,f;
	t=sqrt(24.0*((double)n)+1.0);
	return ((t-modf(t,&f)==t) && (unsigned long long int)t % 6 ==5 );	
}

int main(){
	int i;
	unsigned long long int p[10000]={0};
	unsigned long long int d=0;
	p[0]=1;
	p[1]=5;
	for(i=2;i<10000;i++){
		p[i]=(3*i*i-i)/2;
		for(int k=0;k<i;k++)
			if(is_pentagonal(p[i]+p[k]) && is_pentagonal(p[i]-p[k]))
				d=p[i]-p[k];
		if(d)
			break;
	}
	printf("%llu\n",d);


	
}