#include <stdio.h>
#include <math.h>
/*


The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

     1: 1
     3: 1,3
     6: 1,2,3,6
    10: 1,2,5,10
    15: 1,3,5,15
    21: 1,3,7,21
    28: 1,2,4,7,14,28

We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?


*/

int primes[10000] = {0};
 
 int prime(unsigned long long int n){
	if (n==2 || n==3 || n==5 || n==7)
		return 1;
	if (n % 2 == 0 || n==1)
		return 0;
	unsigned long long int lim=ceil(sqrt(n));
	unsigned long long int i=1;
	do{
		i+=2;
		if ( n % i == 0)
			return 0;
	}while(i<lim);
	return 1;
}

int n_div(unsigned long int n){

	int ret = 1;
	int i = 0;
 unsigned long int div = 1;
	for(i=0;n!=1;i++){
 		if(!(n % primes[i]))
			for(int k = 1;;k++){
				div = 1;
  			if(!(n % primes[i])){
					 div *= primes[i];
					 n/=div;

 				}
 				else{
					ret*=k;
					break;
				}
			}
		if (ret > 500)
			return ret;	

	}

	return ret;



}

    
int main(){

	unsigned long int register i;
	unsigned long int n = 0;
	unsigned long int ret = 0;
	int index =0;
	for(i = 2;index < 10000 ; i++)
		if(prime(i) ){
			primes[index] = i;
 			index++;
		}


	for(i=1;ret < 500 ;i++){

		n = (i*(i + 1))/2;
		 
		ret = n_div(n);


	}
	 printf("%i\n",n);
 

	

}